#!/usr/bin/env bash

# Apply gtk theming
exec_always ~/.config/sway/scripts/import-gsettings

# Set inner/outer gaps
gaps inner 10
gaps outer 5

# Hide titlebar on windows:
default_border pixel 2

# Default Font
font pango:Noto Sans Regular 10

# Thin borders:
# smart_borders on

# Set wallpaper:
exec swaybg -i ~/Pictures/wallpaper/gruvbox/OpMPCR0.png

# Title format for windows
for_window [shell="xdg_shell"] title_format "%title (%app_id)"
for_window [shell="x_wayland"] title_format "%class - %title"

#### Sway Window Colors ####
set $unfocused  #a6a1ae
set $urgent     #f8928a
set $normal     #d3869b
set $inactive   #282828

# colors                    border        bg          text         indicator   chld_brdr
client.focused              $normal     $normal     $unfocused     $normal     $normal
client.focused_inactive     $inactive   $inactive   $unfocused     $inactive   $inactive
client.unfocused            $unfocused  $unfocused  $unfocused     $unfocused  $unfocused
client.urgent               $urgent     $urgent     $unfocused     $urgent     $urgent
client.placeholder          $unfocused  $unfocused  $unfocused     $unfocused  $unfocused
client.background           $unfocused#

# Status Bar:
#
# Read `man 5 sway-bar` for more information about this section.
bar {
    swaybar_command waybar
}
