use_nerdfont = true
album_column = true


[keybindings]
"=" = "volup"
"F" = "seek -10000"
"b" = "seek +10000"
"PageUp" = "move up 10"
"PageDown" = "move down 10"
"L" = "next"
"H" = "previous"
"s" = "shuffle"
"z" = "save"
"p" = "playpause"

# [theme]
# primary = "light white"
# secondary = "black"
# title = "cyan"
# playing = "cyan"
# highlight = "blue"
# highlight_bg = "light black"
# error = "light white"
# error_bg = "red"
# statusbar = "cyan"
# statusbar_progress = "cyan"
# cmdline = "black"
# cmdline_bg = "light white"

[theme]
background = "default"
# background = "black"
primary = "#F8F8F2"
secondary = "light black"
title = "#bd93f9"
playing = "#bd93f9"
playing_selected = "#D0B3FA"
playing_bg = "black"
highlight = "#f8f8f2"
highlight_bg = "#44475a"
error = "#f8f8f2"
error_bg = "#ff5555"
statusbar = "black"
statusbar_progress = "#bd93f9"
statusbar_bg = "#bd93f9"
cmdline = "#f8f8f2"
cmdline_bg = "black"
search_match = "#ff79c6"
