use_nerdfont = true
album_column = true


[keybindings]
"=" = "volup"
"F" = "seek -10000"
"b" = "seek +10000"
"PageUp" = "move up 10"
"PageDown" = "move down 10"
"L" = "next"
"H" = "previous"
"s" = "shuffle"
"z" = "save"
"p" = "playpause"
"s" = "search"

# [theme]
background = "default"
# background = "black"
primary = "#F8F8F2"
secondary = "light black"
title = "#bd93f9"
playing = "#bd93f9"
playing_selected = "#D0B3FA"
playing_bg = "black"
highlight = "#f8f8f2"
highlight_bg = "#44475a"
error = "#f8f8f2"
error_bg = "#ff5555"
statusbar = "black"
statusbar_progress = "#bd93f9"
statusbar_bg = "#bd93f9"
cmdline = "#f8f8f2"
cmdline_bg = "black"
search_match = "#ff79c6"

# [theme]
# background = "default"
# #background = "#2E3440"
# primary = "#D8DEE9"
# secondary = "#4C566A"
# title = "#EBCB8B"
# playing = "#2E3440"
# playing_selected = "#FF6060"
# playing_bg = "#88C0D0"
# highlight = "#88C0D0"
# highlight_bg = "#4C566A"
# error = "#ECEFF4"
# error_bg = "#BF616A"
# statusbar = "#2E3440"
# statusbar_progress = "#A3BE8C"
# statusbar_bg = "#8FBCBB"
# cmdline = "#D8DEE9"
# cmdline_bg = "#2E3440"
# search_match = "#B48EAD"
